dist: trusty
sudo: false
matrix:
  include:
  - language: csharp
    mono: none
    dotnet: 2.1
    before_script:
    - cd TestTemplate/cSharp/ConsoleForT/
    script:
    - dotnet test TestConsoleForT

  - language: node_js
    node_js:
    - '9'
    chche:
      directories:
      - "./node_modules"
    addons:
      chrome: stable
      apt:
        sources:
        - google-chrome
        packages:
        - google-chrome-stable
    before_script:
    - npm install -g codecov
    - npm install coveralls
    - yarn
    - ng lint
    email:
      recipients:
      - "$EMAIL_NOTIFICATION$"
      on_success: never
      on_failure: always
    script:
    - export CHROME_BIN=chromium-browser
    - xvfb-run -a npm run test -- --browsers=ChromeNoSandbox --code-coverage --watch=false
    - xvfb-run -a npm run e2e --
    after_success:
    - codecov





